version: '3.8'
services:
    nginx:
        build: docker/nginx
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./app:${APP_DIR}"
            - "./logs/nginx:/var/log/nginx"
    php:
        build: docker/php-fpm
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        volumes:
            - "./app:${APP_DIR}"
            - "./logs/supervisor:/var/log/supervisor"
            - "./logs/php-fpm:/var/log/php-fpm"
        expose:
            - "9000"
    mysql:
        build: docker/mysql
        restart: always
        ports:
            - "${MYSQL_PORT}:3306"
        expose:
            - 3306
        environment:
            - TZ=$TZ
            - LANG=$LANG
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - "./data/mysql:/var/lib/mysql"
    redis:
        build: docker/redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        expose:
            - 6379
        environment:
            - TZ=$TZ
            - LANG=$LANG
        volumes:
            - "./data/redis:/data"
