version: '3.8'
services:
    nginx:
        build: docker/nginx
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./app:${APP_DIR}"
            - "./logs/nginx:/var/log/nginx"
    php:
        build: docker/php-fpm
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        volumes:
            - "./app:${APP_DIR}"
            - "./logs/supervisor:/var/log/supervisor"
            - "./logs/php-fpm:/var/log/php-fpm"
        expose:
            - "9000"
